### ISSUE TITLE
Production output contains Function constructor

### ISSUE THREAD

**Issue by t-miller** [Kocal/vue-web-extension#658]
**Describe the bug**
After running `yarn build`, the generated files still contain the `Function()` constructor. Upon trying to upload an extension to the Firefox store, the linter states `The Function constructor is eval.` in both `content-script.js` and `background.js`. I have kept the OOTB `vue.config.js` and `babel.config.js`.

**To Reproduce**
1. Fix `background.js` to point to `js/content-script.js`
2. Run `yarn build`

**Expected behavior**
The output files to be free of `eval()` and `Function()` to comply with Mozilla's CSP.

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: 2.0.0
 - OS: Windows 10 Pro - 19042.746
 - Node.js version: 14.15.4

**Comment by Kocal** [comment]
Hi,

This is maybe due to the usage of the Vue runtime compiler, see https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only, but the option [`runtimecompiler`](https://cli.vuejs.org/config/#runtimecompiler) is disabled by default.

However, this time it looks like it's not coming from Vue but from Webpack itself:
![Capture d’écran de 2021-01-23 22-22-46](https://user-images.githubusercontent.com/2103975/105614402-8a98a000-5dc9-11eb-855b-fdea8e09dda0.png)

I remember that I fixed the same issue previously in version 1.x, see #398. In our case with version 2.x, we must configure Vue-CLI/Webpack like this: 

```
// vue.config.js

const webpack = require('webpack');

module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.DefinePlugin({
        global: 'window',
      }),
    ],
  },
  // ...
}

**Comment by t-miller** [comment]
Yeah, I tried setting Vue to evaluating to the `runtime.esm` version to no avail. I'll give your webpack config a shot, and let you know, thanks!

**Comment by Kocal** [comment]
I've opened a PR to fix the issue https://github.com/adambullmer/vue-cli-plugin-browser-extension/pull/110

If this get merged, you will have to update `vue-cli-plugin-browser-extension` and it should be okay.

**Comment by t-miller** [comment]
Hey @Kocal - that didn't appear to fix the issue for me. I've created a [test repo](https://github.com/t-miller/test-vue-webextension/tree/0.1.0) and attached the build [output ](https://github.com/t-miller/test-vue-webextension/releases/tag/0.1.0)after adding the webpack config. I still get the following `The Function constructor is eval.` warnings when I upload to the Firefox Developer Hub. 

![image](https://user-images.githubusercontent.com/19845698/105745523-5e396c80-5f0c-11eb-8738-6386aeda0cd3.png)

**Comment by Kocal** [comment]
Hey, and thanks for your repository!

I've analyzed the generated `js/background.js` and its sourcemap with [source-map-visualization](https://gist.github.com/Kocal/c055a9ea3fcbc4df1d99c86270af4ca9) (sorry for the Gist, but the link is sooooo long to be used in a comment or with git.io :smile:) and this is what I found:

- line 1 column 5089: due to `/node_modules/core-js/internals/task.js`, ![image](https://user-images.githubusercontent.com/2103975/105761779-d37c6000-5f53-11eb-8f9b-52e20554648d.png)
- line 1 column 28457: due to `/node_modules/core-js/internals/global.js`, ![image](https://user-images.githubusercontent.com/2103975/105761924-ff97e100-5f53-11eb-8c19-7a0177d0b7eb.png)

I suppose the other issues for `js/content-script.js` and `js/chunk-vendors.[hash].js` are the same.

Since it's coming from core-js itself (see related issue https://github.com/zloirock/core-js/issues/86), I don't think I can do something about that...
Maybe use a Webpack hook to replace `|| new Function('return this')()` by something else while/after transpiling files... :shrug:

**Comment by t-miller** [comment]
I appreciate the analysis! I'll see what I can do, thanks!

**Comment by jsonwu5** [comment]
This problem still exists. Is there a solution?

**Comment by t-miller** [comment]
I never found a solution sadly

**Comment by Kocal** [comment]
What about:
> Maybe use a Webpack hook to replace `|| new Function('return this')()` by something else while/after transpiling files... 🤷

from https://github.com/Kocal/vue-web-extension/issues/658#issuecomment-767101336?
